# -*- coding: utf-8 -*-
r"""Emit results/tables/tab_singlerate.tex from the single-rate separation study.

Generated rather than hand-written, for the reason the other tables are: a table
typed out of a log drifts from the log the first time the study is re-run, and
nothing catches it.

    python code/table_singlerate.py
"""
from __future__ import annotations

import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results", "theory")
OUT = os.path.join(HERE, "..", "results", "tables", "tab_singlerate.tex")

d = json.load(io.open(os.path.join(RES, "singlerate.json"), encoding="utf-8"))
cfg, sizes, bias = d["config"], d["by_size"], d["step_sd_bias"]
a_c, b_c, g_c = d["fitted"]["consistent"]
a_n, b_n, g_n = d["fitted"]["naive"]

rows = []
for k in sorted(sizes, key=int):
    r = sizes[k]
    rows.append(f"${r['records']}$ & ${r['increments']}$ & "
                f"${r['mean_2dLL']:.0f}$ & "
                f"${100*r['frac_clearly_separated']:.0f}$ & "
                f"${100*r['frac_consistent_better']:.0f}$\\\\")

QLABEL = [("q5", "$5$"), ("q25", "$25$"), ("q50", "$50$"),
          ("q75", "$75$"), ("q95", "$95$")]
bias_cells = " & ".join(f"${100*bias[k]['rel_err']:+.0f}$" for k, _ in QLABEL)
head_cells = " & ".join(lab for _, lab in QLABEL)

tex = rf"""%  generated by code/table_singlerate.py -- do not edit
\begin{{table}}[htbp]
\centering
\caption{{Both parameterisations fitted by maximum likelihood to run-to-failure
paths of the coupled consistent process at one fixed interval, ${cfg['reps']}$ data
sets per row. $2\Delta\ell$: twice the log-likelihood advantage of the consistent
fit; separated: $2\Delta\ell>\chi^2_{{1,0.999}}$; correct: the consistent fit wins.}}
\label{{tab:singlerate}}
\begin{{tabular}}{{@{{}}rrrrr@{{}}}}
\toprule
records & increments & $2\Delta\ell$ & separated (\%) & correct (\%)\\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}

\vspace{{6pt}}
\begin{{minipage}}{{0.95\linewidth}}\footnotesize
Lower panel: error of the naive fit in the step s.d., by percentile of damage, on
${d.get('fit_increments', sizes[max(sizes, key=int)]['increments'])}$ increments with
$\alpha={cfg['alpha']}$, $\beta={cfg['beta']:g}$, $\gamma={cfg['gamma']}$; the
consistent fit recovers $\alpha={a_c:.3f}$, the naive one shrinks it to ${a_n:.3f}$.

\vspace{{3pt}}
\centering
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
percentile of damage & {head_cells}\\
error in step s.d.\ (\%) & {bias_cells}\\
\bottomrule
\end{{tabular}}
\end{{minipage}}
\end{{table}}
"""

io.open(OUT, "w", encoding="utf-8", newline="").write(tex)
print(f"  wrote {os.path.relpath(OUT, os.path.dirname(HERE))}")
for line in rows:
    print("   ", line.replace("\\\\", ""))
